export const AISLES = [
  'Produce',
  'Meat & fish',
  'Dairy & eggs',
  'Bakery',
  'Spices & seasonings',
  'Pantry',
  'Frozen',
  'Drinks',
  'Other',
] as const;
export type Aisle = (typeof AISLES)[number];

/** Common ingredients by aisle. Used for aisle grouping, autocomplete and classification. */
const BY_AISLE: Record<Exclude<Aisle, 'Other'>, string[]> = {
  Produce: [
    'onion',
    'red onion',
    'spring onion',
    'shallot',
    'garlic',
    'ginger',
    'tomato',
    'cherry tomato',
    'potato',
    'sweet potato',
    'carrot',
    'celery',
    'cucumber',
    'lettuce',
    'spinach',
    'cabbage',
    'cauliflower',
    'broccoli',
    'peas',
    'green beans',
    'okra',
    'aubergine',
    'eggplant',
    'courgette',
    'zucchini',
    'bell pepper',
    'pepper',
    'capsicum',
    'green chilli',
    'green chili',
    'chilli',
    'chili',
    'jalapeño',
    'mushroom',
    'leek',
    'pumpkin',
    'squash',
    'beetroot',
    'radish',
    'corn',
    'avocado',
    'lemon',
    'lime',
    'orange',
    'apple',
    'banana',
    'mango',
    'berries',
    'strawberry',
    'blueberry',
    'raspberry',
    'grapes',
    'pineapple',
    'pear',
    'peach',
    'dates',
    'coriander',
    'cilantro',
    'mint',
    'parsley',
    'basil',
    'dill',
    'thyme',
    'rosemary',
    'sage',
    'curry leaves',
    'fenugreek leaves',
    'methi',
    'lemongrass',
    'kale',
    'fresh herbs',
    'scallion',
    'bok choy',
    'asparagus',
    'fennel',
    'turnip',
    'yam',
    'plantain',
    'coconut',
  ],
  'Meat & fish': [
    'chicken',
    'chicken breast',
    'chicken thighs',
    'beef',
    'mince',
    'minced beef',
    'ground beef',
    'lamb',
    'mutton',
    'goat',
    'pork',
    'bacon',
    'sausage',
    'ham',
    'turkey',
    'duck',
    'fish',
    'salmon',
    'cod',
    'tuna',
    'prawns',
    'shrimp',
    'crab',
    'mussels',
    'anchovies',
    'keema',
    'steak',
    'ribs',
    'liver',
  ],
  'Dairy & eggs': [
    'milk',
    'butter',
    'ghee',
    'cream',
    'double cream',
    'heavy cream',
    'sour cream',
    'yogurt',
    'yoghurt',
    'curd',
    'cheese',
    'cheddar',
    'mozzarella',
    'parmesan',
    'feta',
    'paneer',
    'ricotta',
    'cream cheese',
    'egg',
    'eggs',
    'buttermilk',
    'condensed milk',
    'evaporated milk',
    'khoya',
    'malai',
  ],
  Bakery: ['bread', 'naan', 'pita', 'tortilla', 'roti', 'buns', 'rolls', 'breadcrumbs', 'croissant', 'bagel', 'puff pastry'],
  'Spices & seasonings': [
    'salt',
    'black pepper',
    'pepper',
    'red chilli powder',
    'chilli powder',
    'chili powder',
    'chilli flakes',
    'paprika',
    'cayenne',
    'turmeric',
    'haldi',
    'cumin',
    'cumin seeds',
    'jeera',
    'coriander powder',
    'coriander seeds',
    'garam masala',
    'masala',
    'cardamom',
    'green cardamom',
    'black cardamom',
    'cloves',
    'cinnamon',
    'cinnamon stick',
    'bay leaf',
    'bay leaves',
    'star anise',
    'nutmeg',
    'mace',
    'fennel seeds',
    'mustard seeds',
    'fenugreek',
    'kasuri methi',
    'saffron',
    'oregano',
    'dried oregano',
    'dried thyme',
    'mixed herbs',
    'curry powder',
    'chaat masala',
    'amchur',
    'asafoetida',
    'hing',
    'sesame seeds',
    'nigella seeds',
    'carom seeds',
    'ajwain',
    'vanilla',
    'vanilla extract',
    'baking powder',
    'baking soda',
    'bicarbonate of soda',
    'yeast',
    'stock cube',
    'bouillon',
  ],
  Pantry: [
    'rice',
    'basmati rice',
    'flour',
    'plain flour',
    'all-purpose flour',
    'self-raising flour',
    'wholemeal flour',
    'atta',
    'gram flour',
    'besan',
    'cornflour',
    'cornstarch',
    'semolina',
    'sugar',
    'brown sugar',
    'caster sugar',
    'icing sugar',
    'jaggery',
    'honey',
    'maple syrup',
    'oil',
    'olive oil',
    'vegetable oil',
    'sunflower oil',
    'mustard oil',
    'sesame oil',
    'coconut oil',
    'vinegar',
    'soy sauce',
    'fish sauce',
    'ketchup',
    'mayonnaise',
    'mustard',
    'tomato paste',
    'tomato puree',
    'chopped tomatoes',
    'canned tomatoes',
    'coconut milk',
    'stock',
    'chicken stock',
    'vegetable stock',
    'broth',
    'pasta',
    'spaghetti',
    'noodles',
    'lentils',
    'red lentils',
    'dal',
    'daal',
    'chickpeas',
    'kidney beans',
    'black beans',
    'beans',
    'oats',
    'raisins',
    'almonds',
    'cashews',
    'peanuts',
    'walnuts',
    'pistachios',
    'nuts',
    'peanut butter',
    'chocolate',
    'cocoa powder',
    'chocolate chips',
    'tamarind',
    'ginger garlic paste',
    'garlic paste',
    'ginger paste',
    'rose water',
    'kewra water',
    'vermicelli',
    'breadcrumbs',
    'couscous',
    'quinoa',
    'water',
  ],
  Frozen: ['frozen peas', 'frozen spinach', 'ice cream', 'frozen corn', 'frozen berries', 'ice'],
  Drinks: ['wine', 'white wine', 'red wine', 'beer', 'juice', 'orange juice', 'lemon juice', 'lime juice', 'coffee', 'tea', 'soda'],
};

const ENTRIES: [string, Aisle][] = Object.entries(BY_AISLE)
  .flatMap(([aisle, names]) => names.map((n) => [n, aisle as Aisle] as [string, Aisle]))
  .sort((a, b) => b[0].length - a[0].length);

/** Lower-case, singular-ish key for matching ("Onions" → "onion"). */
export function ingredientKey(name: string): string {
  return name
    .toLowerCase()
    .replace(/\([^)]*\)/g, '')
    .replace(/[^\p{L}\p{N}\s-]/gu, '')
    .replace(/\s+/g, ' ')
    .trim()
    .split(' ')
    .map(singular)
    .join(' ');
}

export function singular(word: string): string {
  if (word.length <= 3) return word;
  if (/(?:ss|us|is)$/.test(word)) return word;
  if (/ies$/.test(word)) return word.slice(0, -3) + 'y';
  if (/(?:tomato|potato|mango)es$/.test(word)) return word.slice(0, -2);
  if (/(?:ch|sh|x)es$/.test(word)) return word.slice(0, -2);
  if (/ves$/.test(word) && !/(?:olive|clove|chive)s$/.test(word)) return word.slice(0, -3) + 'f';
  if (/s$/.test(word)) return word.slice(0, -1);
  return word;
}

const KEYED: [string, Aisle][] = ENTRIES.map(([n, a]) => [ingredientKey(n), a]);

/** Which aisle an ingredient belongs to, by the longest known name it contains. */
export function aisleFor(name: string): Aisle {
  const key = ` ${ingredientKey(name)} `;
  for (const [known, aisle] of KEYED) {
    if (key.includes(` ${known} `)) return aisle;
  }
  return 'Other';
}

/** Is this (short) phrase a known ingredient? */
export function isKnownIngredient(name: string): boolean {
  return aisleFor(name) !== 'Other';
}
